### ISSUE TITLE
bug(doors): Ghosts are able to block doors

### ISSUE THREAD

**Issue by briankwlin** [Extacy/Ghost#1]
Hi @Extacy ,

Our community is running your plugin (thank you!) but we're encountering some issues with the latest fix you made to prevent Ts from opening doors. While doors aren't opened when Ts attempt to open them, when certain doors are opened, when they attempt to close automatically if there is a ghost in between the door the door won't close. See the below door:

https://i.imgur.com/4LNBFLu.jpg

Thanks (: let me know if you need anything else to reproduce this issue.

**Comment by Extacy** [comment]
@brian1999lin Do you have a map I can test this on? I tried making my own map but I can't reproduce it.

**Comment by briankwlin** [comment]
Yep, armory door on this map: https://steamcommunity.com/sharedfiles/filedetails/?id=507214544. Same door from the screenshot above.
