### ISSUE TITLE
feat(teleporters): Allow ghosts to use teleporters

### ISSUE THREAD

**Issue by briankwlin** [Extacy/Ghost#2]
Hey @Extacy ,

A feature I'd love to see is ghosts being able to use teleporters. This way they can get around certain maps that may be confusing to navigate in noclip.

Thanks!

**Comment by Extacy** [comment]
https://github.com/Extacy/Ghost/blob/889dabe15d6fd88aba4461393d4662087c967cfa/addons/sourcemod/scripting/ghost.sp#L383-L407

This should work.. Do you have a map I can test this on?

**Comment by briankwlin** [comment]
Yep, here: https://steamcommunity.com/sharedfiles/filedetails/?id=507214544

Go into the first cell on the lower level (right by isolation), break the vent at the back of the cell, and try to walk through the teleporter.

**Comment by briankwlin** [comment]
@Extacy Just following up on this, thanks (:

**Comment by Extacy** [comment]
sorry for the delay 🙃 was a bit busy and wasn't too sure what the issue was

**Comment by briankwlin** [comment]
@Extacy Thanks for following up :) unfortunately this bug is still occurring with the map I linked earlier and the same mentioned teleporter.
