### ISSUE TITLE
Add translations for messages

### ISSUE THREAD

**Issue by crashzk** [Extacy/Ghost#4]
Add translations for the messages that the plugin displays.

**Comment by Extacy** [comment]
Sorry for the delay! For some reason I didn't receive a notification for this issue.
I'll work on this soon

**Comment by Extacy** [comment]
@crashzk Feel free to make a PR for another language if you want (I'm assuming that's the reason for this issue)

**Comment by crashzk** [comment]
Exactly, thank you very soon I will send you a PR with the new translation, thank you!
