### ISSUE TITLE
Infinite velocity doesn't surpass CS:GO cap

### ISSUE THREAD

**Issue by briankwlin** [Extacy/Ghost#8]
CS:GO has a native speed cap of ~300 velocity, but even with "speed" enabled in the plugin, a ghost is unable to surpass the cap.

Repro: https://www.youtube.com/watch?v=cOjjbL-aMb4

@Extacy

**Comment by Extacy** [comment]
Hi, sorry basically forgetting about this issue. The ConVar "sv_enablebunnyhopping" is what is used to allow players to exceed maximum velocity, and the ConVar SHOULD be client replicated.

However, this must be a bug in CSGO, as the ConVar is NOT client replicated, and so unlimited speed does not work. (Unless the ConVar is set for every player through the server console).
